### ISSUE TITLE
Authorization Middleware

### ISSUE THREAD

**Issue by Noorin99** [Noorin99/HomeTaste#8]
### Tasks to complete: 
<hr>

- [x] Implement middleware for role-based authorization to differentiate between cookers and customers.
- [x] Configure the middleware to check the role of the user based on their JWT token.
- [x] Apply the authorization middleware to the necessary routes.
